version: '3.8'
services:
  bankingservice:
    build: ./bankingservice
    ports:
      - 8080:8080
    environements:
      - SPRING_.APPLICATION.NAME = bankingservice
      - server_port = 8080
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI = https://github.com/bankingProject-21T2342/Cloud-conf.git
    
    networks:
      - bankingnetwork

  bank-registry-service:
    build: ./bank-registry-service
    ports:
      - 8761:8761
    environements:
      - SPRING_APPLICATION_NAME = bank-registry-service
      - SPRING_CLOUD_CONFIG_URI = http://bankingservice:8080
      - SPRING_CONFIG_IMPORT = configserver:http://bankingservice:8080
    depends_on:
      - servicename: bankingservice
        condition: service_healthy  

    networks:
      - bankingnetwork
  
  mysqlbank-user-db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bank_user_db
    ports:
      - 3306:3307
    networks:
      - bankingnetwork
  
  bank-user-service:
    build: ./bank-user-services
    ports:
      - 8081:8081
    environements:
      - SPRING_APPLICATION_NAME = bank-user-service
      - SPRING_CLOUD_CONFIG_URI = http://bankingservice:8080
      - SPRING_CONFIG_IMPORT = configserver:http://bankingservice:8080
    
    depends_on:
      - servicename: bank
        condition: service_healthy
      
      - servicename: mysqlbank-user-db
        condition: service_healthy

    networks:
      - bankingnetwork

  bank-proxy-service:
    build: ./bank-proxy-service
    ports:
      - 8082:8082
    environements:
      - SPRING_APPLICATION_NAME = bank-proxy-service
      - SPRING_CLOUD_CONFIG_URI = http://bankingservice:8080
      - SPRING_CONFIG_IMPORT = configserver:http://bankingservice:8080
    depends_on:
      - servicename: bankingservice
        condition: service_healthy
    networks:
      - bankingnetwork
networks:
  bankingnetwork:
    driver: bridge